# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_block/mb_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block || ORIG_REF_NAME==mb_block} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_0 || ORIG_REF_NAME==mb_block_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_v10_0/mb_block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_v10_0 || ORIG_REF_NAME==mb_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_v10_0 || ORIG_REF_NAME==mb_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_0/mb_block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_0/mb_block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_lmb_bram_0/mb_block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_lmb_bram_0 || ORIG_REF_NAME==mb_block_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_xbar_0 || ORIG_REF_NAME==mb_block_xbar_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_periph_0/mb_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_mdm_1_0/mb_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_mdm_1_0 || ORIG_REF_NAME==mb_block_mdm_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_clk_wiz_1_0 || ORIG_REF_NAME==mb_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_uartlite_0_0 || ORIG_REF_NAME==mb_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_gpio_3_0/mb_block_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_gpio_3_0 || ORIG_REF_NAME==mb_block_axi_gpio_3_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_gpio_3_1/mb_block_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_gpio_3_1 || ORIG_REF_NAME==mb_block_axi_gpio_3_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_gpio_3_2/mb_block_axi_gpio_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_gpio_3_2 || ORIG_REF_NAME==mb_block_axi_gpio_3_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_timer_0_0 || ORIG_REF_NAME==mb_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_block_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_xlconcat_0_0/mb_block_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_xlconcat_0_0 || ORIG_REF_NAME==mb_block_xlconcat_0_0} -quiet] -quiet

# IP: ip/over_rom_1/over_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==over_rom || ORIG_REF_NAME==over_rom} -quiet] -quiet

# IP: ip/zero_rom_1/zero_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zero_rom || ORIG_REF_NAME==zero_rom} -quiet] -quiet

# IP: ip/two_rom_1/two_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==two_rom || ORIG_REF_NAME==two_rom} -quiet] -quiet

# IP: ip/three_rom_1/three_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==three_rom || ORIG_REF_NAME==three_rom} -quiet] -quiet

# IP: ip/four_rom_1/four_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==four_rom || ORIG_REF_NAME==four_rom} -quiet] -quiet

# IP: ip/six_rom_1/six_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==six_rom || ORIG_REF_NAME==six_rom} -quiet] -quiet

# IP: ip/eight_rom_1/eight_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eight_rom || ORIG_REF_NAME==eight_rom} -quiet] -quiet

# XDC: e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/mb_block_ooc.xdc
