# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/xilinx/final_project/lab6.runs/synth_1/mb_usb_hdmi_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/xilinx/final_project/lab6.cache/wt [current_project]
set_property parent.project_path E:/xilinx/final_project/lab6.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/hdmi_tx_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo e:/xilinx/final_project/lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files E:/xilinx/red_brick/red_brick.COE
add_files E:/xilinx/tank3/tank3.COE
add_files E:/xilinx/s_bullet/s_bullet.COE
add_files E:/xilinx/final_project/lab6.srcs/sources_1/brick_long/brick_long.COE
add_files E:/xilinx/final_project/lab6.srcs/sources_1/tank3/tank3.COE
add_files E:/xilinx/final_project/lab6.srcs/sources_1/brick_t/brick_t.COE
add_files E:/xilinx/final_project/lab6.srcs/sources_1/i/i.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/1/1.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/two/two.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/three/three.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/four/four.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/five/five.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/six/six.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/seven/seven.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/eight/eight.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/nine/nine.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/sc/sc.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/zero.COE
add_files e:/xilinx/final_project/lab6.srcs/sources_1/over/over.COE
read_verilog -library xil_defaultlib -sv {
  E:/xilinx/final_project/lab6.srcs/sources_1/new/block.sv
  F:/新建文件夹/hex_driver.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/red_brick/red_brick_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/red_brick/red_brick_palette.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/tank3/tank3_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/新建文件夹/mb_usb_hdmi_top.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/tank2.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/tank2_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/missle.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/s_bullet/s_bullet_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/新建文件夹/ball.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/新建文件夹/VGA_controller.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/missle2.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/destroy_wall_sm.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/enemy_tank.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/enemy_missle.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/timer.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/block2.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/brick_t/brick_t_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/base.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/i/i_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/music_font.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/music_controller.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/imports/music.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/1/1_palette.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/1/1_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/block3.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/new/brick2_t_example.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/over/over_palette.sv
  E:/xilinx/final_project/lab6.srcs/sources_1/over/over_example.sv
}
read_verilog -library xil_defaultlib E:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/hdl/mb_block_wrapper.v
add_files E:/xilinx/final_project/lab6.srcs/sources_1/bd/mb_block/mb_block.bd
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_dlmb_v10_0/mb_block_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_0/mb_block_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_0/mb_block_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_lmb_bram_0/mb_block_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_mdm_1_0/mb_block_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_mdm_1_0/mb_block_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_0/mb_block_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_0/mb_block_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_0/mb_block_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_1/mb_block_axi_gpio_3_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_1/mb_block_axi_gpio_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_1/mb_block_axi_gpio_3_1.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_2/mb_block_axi_gpio_3_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_2/mb_block_axi_gpio_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_3_2/mb_block_axi_gpio_3_2.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/mb_block_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/one_rom/one_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/one_rom/one_rom_ooc.xdc]

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/red_brick_rom/red_brick_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/red_brick_rom/red_brick_rom_ooc.xdc]

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/tank3_rom/tank3_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/tank3_rom/tank3_rom_ooc.xdc]

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/frame_buffer_0/frame_buffer_0.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/frame_buffer_0/frame_buffer_0_ooc.xdc]

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/bullet_rom/bullet_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/bullet_rom/bullet_rom_ooc.xdc]

read_ip -quiet E:/xilinx/final_project/lab6.srcs/sources_1/ip/i_rom/i_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/i_rom/i_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/two_rom/two_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/two_rom/two_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/three_rom/three_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/three_rom/three_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/four_rom/four_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/four_rom/four_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/five_rom/five_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/five_rom/five_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/six_rom/six_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/six_rom/six_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/seven_rom/seven_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/seven_rom/seven_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/eight_rom/eight_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/eight_rom/eight_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/nine_rom/nine_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/nine_rom/nine_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/score_rom/score_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/score_rom/score_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/zero_rom/zero_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/zero_rom/zero_rom_ooc.xdc]

read_ip -quiet e:/xilinx/final_project/lab6.srcs/sources_1/ip/over_rom/over_rom.xci
set_property used_in_implementation false [get_files -all e:/xilinx/final_project/lab6.gen/sources_1/ip/over_rom/over_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc
set_property used_in_implementation false [get_files F:/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/xilinx/final_project/lab6.srcs/utils_1/imports/synth_1/mb_intro_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mb_usb_hdmi_top -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_usb_hdmi_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_usb_hdmi_top_utilization_synth.rpt -pb mb_usb_hdmi_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
