# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/xilinx/final_project/lab6.srcs/sources_1/ip/score_rom/score_rom.xci
# IP: The module: 'score_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xilinx/final_project/lab6.gen/sources_1/ip/score_rom/score_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'score_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/xilinx/final_project/lab6.srcs/sources_1/ip/score_rom/score_rom.xci
# IP: The module: 'score_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xilinx/final_project/lab6.gen/sources_1/ip/score_rom/score_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'score_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
